home:
    path: /
    controller: App\Controller\HomeController
    methods: [GET]

keyboardman_filesystem_api:
    resource: '@KeyboardmanFilesystemBundle/Resources/config/routes.yaml'

keyboardman_filemanager:
    resource: '@KeyboardmanFilemanagerBundle/Resources/config/routes.yaml'

demo_picker:
    path: /demo-picker
    controller: App\Controller\DemoPickerController
    methods: [GET, POST]
