keyboardman_filesystem:
    api:
        max_upload_size: 100M
    filesystems:
        default:
            adapter: app.flysystem_adapter.local
        s3:
            adapter: app.flysystem_adapter.s3
